name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build  # Replace with your build output directory
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Change if you want to use a different branch for GitHub Pages
